Add Modal Dialog
UKHO/admiralty-design-system pull request #176
Opened 2024-03-19 17:36 UTC by UKHOGreg

2024-05-07 13:04 UTC, ecstaticrainbow requested changes

2024-05-07 13:04 UTC, ecstaticrainbow commented on packages/website/src/app/components/modal-dialog/modal-dialog.mdx
> +A.
We need some actual words in here

2024-05-07 13:04 UTC, ecstaticrainbow commented on packages/website/src/app/components/modal-dialog/modal-dialog.mdx
> +A.
Same here

2024-05-15 14:44 UTC, UKHOGreg commented on packages/website/src/app/components/modal-dialog/modal-dialog.mdx
> +A.
Done

2024-05-15 14:44 UTC, UKHOGreg commented on packages/website/src/app/components/modal-dialog/modal-dialog.mdx
> +A.
Done

2024-05-21 08:52 UTC, ecstaticrainbow submitted a review, later dismissed
Just one thing regarding the slot JSDoc

2024-05-21 14:24 UTC, UKHOGreg commented on packages/core/src/components/modal-dialog/modal-dialog.tsx
> +@Component({
Done!

2024-05-23 11:47 UTC, ecstaticrainbow approved these changes
LGTM

2024-05-23 11:58 UTC, merged