feature: header items should be links
UKHO/admiralty-design-system pull request #233
Opened 2024-08-01 12:48 UTC by buzzub

Resolves [158](https://github.com/UKHO/admiralty-design-system/issues/158)

The links in the header / navigation menu component are rendered using buttons that emit events. For better accessibility, links should be rendered using `<a>` rather than a `<button>`.

To ensure compatibility with existing implementations, a new component `<AdmiraltyHeaderMenuLink/>` has been created. This accepts a `href` prop and will render an `<a>` tag. This will give the appearance of a link for users (hover shows the target) and correctly reads out a link for screen readers.

For compatibility with frameworks that use routers for navigation e.g. `router.push('/home')` the default browser redirect behaviour for the link can be suppressed using the `suppressRedirect` prop. When the link is clicked the `menuItemClick` event is emitted and the router navigation can be used instead of forcing the browser to do a full page reload.

<details>
  <summary>📦 Published PR as canary version: <code>0.21.0--canary.233.2642994.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @ukho/admiralty-angular@0.21.0--canary.233.2642994.0
  npm install @ukho/admiralty-core@0.21.0--canary.233.2642994.0
  # or 
  yarn add @ukho/admiralty-angular@0.21.0--canary.233.2642994.0
  yarn add @ukho/admiralty-core@0.21.0--canary.233.2642994.0
  ```
</details>

2024-08-06 10:14 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/javascript.mdx
Just want to check this

2024-08-06 10:14 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/angular.mdx
Just want to check this

2024-08-06 10:45 UTC, UKHOGreg requested changes

2024-08-06 10:45 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/javascript.mdx
> +    active="{false}"
```suggestion
    active="false"
```

2024-08-06 10:45 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/javascript.mdx
> +    suppress-redirect="{true}"
```suggestion
    suppress-redirect="true"
```

2024-08-06 10:45 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/angular.mdx
> +    active="{false}"
```suggestion
    active="false"
```

2024-08-06 10:45 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/angular.mdx
> +    suppress-redirect="{true}"
```suggestion
    suppress-redirect="true"
```

2024-08-08 10:42 UTC, UKHOGreg requested changes

2024-08-08 10:42 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/javascript.mdx
I have the same issue with the latest javascript example

2024-08-08 14:37 UTC, UKHOGreg submitted a review, later dismissed

2024-08-08 14:37 UTC, UKHOGreg commented on packages/website/src/usage/header/menu-item/javascript.mdx
> +  />
```suggestion
    slot="items">
  </admiralty-header-menu-link>
```

2024-09-05 09:48 UTC, ecstaticrainbow approved these changes
LGTM

2024-09-05 10:42 UTC, merged