New Tabgroup web component
UKHO/admiralty-design-system pull request #33
Opened 2023-05-19 15:38 UTC by tellyzap

<details>
  <summary>📦 Published PR as canary version: <code>0.0.8--canary.33.ef86576.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @ukho/admiralty-angular@0.0.8--canary.33.ef86576.0
  npm install @ukho/admiralty-core@0.0.8--canary.33.ef86576.0
  # or 
  yarn add @ukho/admiralty-angular@0.0.8--canary.33.ef86576.0
  yarn add @ukho/admiralty-core@0.0.8--canary.33.ef86576.0
  ```
</details>

2023-05-30 17:07 UTC, UKHOGreg requested changes

2023-05-31 08:30 UTC, martind-bjss commented on packages/core/src/components/Keys.ts
Only capitalised as it is an enum.  The original enum, which I've moved and added to, was also capitalised.

2023-05-31 08:31 UTC, martind-bjss commented on packages/core/src/components/tab/test/tab.e2e.ts
Yes.  When you run `stencil generate` to create a new component, it puts the test files in a new `test` subdirectory.

2023-06-06 08:33 UTC, UKHOGreg approved these changes

2023-06-06 08:33 UTC, merged