Header Components - tab through navigation using keyboard
UKHO/admiralty-design-system pull request #62
Opened 2023-06-28 11:32 UTC by martind-bjss

2023-07-07 14:42 UTC, UKHOGreg requested changes

2023-07-07 14:42 UTC, UKHOGreg commented on packages/core/src/components/header-menu-item/header-menu-item.scss
> +      // }
comment should be removed?

2023-07-07 14:42 UTC, UKHOGreg commented on packages/core/src/components/header-menu-item/header-menu-item.tsx
> +    console.log('clicked!');
remove log?

2023-07-07 14:42 UTC, UKHOGreg commented on packages/core/src/components/header-menu-item/header-menu-item.tsx
> +    console.log('clicked-subMenuExists, display:', subMenu.style.display);
remove log?

2023-07-07 14:42 UTC, UKHOGreg commented on packages/core/src/components/header-menu-item/header-menu-item.tsx
>     * Handles mouseover events, used to set the aria hidden attribute when submenu
mouseout event, right?

2023-07-25 10:38 UTC, UKHOGreg commented
Header with no title still focuses on the empty title

![image](https://github.com/UKHO/admiralty-design-system/assets/51328760/35b84cb0-8926-42c2-ad4b-34a6b3543e93)

2023-07-25 10:49 UTC, ecstaticrainbow commented
I think we should not render the title html if the title prop is falsey, just to avoid unnecessary tab stops

2023-07-26 10:38 UTC, ecstaticrainbow approved these changes
LGTM

2023-07-26 13:51 UTC, UKHOGreg commented
UI review on TB's behalf

2023-07-26 13:52 UTC, merged